### ISSUE TITLE
Verification links

### ISSUE THREAD

**Issue by Bellomk** [desoukya/SEMS#41] opened 2016-03-09 13:38 UTC
The resend button is fixed and sends verification links whenever I click it, but the issue is now in the links themselves. When I click on them, a new tab is opened but nowhere is reached. It always says "webpage is not available"

**Comment by alihassan0** [comment] 2016-03-09 14:45
thank you for submitting this issue @Bellomk  .. 

we will look into that now in shaa' Allah

**Comment by abdelrahman-elkady** [comment] 2016-03-09 14:53
Duplicate of #40

**Closed as completed by abdelrahman-elkady** 2016-03-09 14:53 UTC
Labels: duplicate

**Comment by abdelrahman-elkady** [comment] 2016-03-09 16:14
@Bellomk That should be fixed now, re-open if anything went wrong

**Comment by Bellomk** [comment] 2016-03-09 16:27
It's working well now. Thank you
